services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    restart: always
    ports:
      - '2181:2181'
    expose:
      - '2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - '9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    expose:
      - '8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    volumes:
      - ./docker/kafka/schemas:/schemas
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 10s
      timeout: 5s
      retries: 5


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081

  schema-init:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-init
    depends_on:
      schema-registry:
        condition: service_healthy
    volumes:
      - ./kafka/schemas:/kafka/schemas
      - ./kafka/init-schema.sh:/tmp/init-schema.sh
    entrypoint: >
      bash -c "
        cp /tmp/init-schema.sh /tmp/init-schema-fixed.sh &&
        sed -i 's/\r$//' /tmp/init-schema-fixed.sh &&
        chmod +x /tmp/init-schema-fixed.sh &&
        bash /tmp/init-schema-fixed.sh
      "

    restart: "no"

  db:
    image: mysql:8.4
    container_name: lending-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u user -p password"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço para criar tópico e registrar o Schema Avro
  init-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: init-kafka
    depends_on:
      - kafka
      - schema-registry
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      echo 'Aguardando o broker iniciar...';
      kafka-topics --bootstrap-server kafka:29092 --list;
      
      echo 'Criando o tópico...';
      kafka-topics --create --topic propostas --bootstrap-server kafka:29092 --partitions 3 --replication-factor 1 || true;
      
      echo 'Tópico criado com sucesso!';
      "

volumes:
  db-data: