-- Tabela Client
CREATE TABLE IF NOT EXISTS CLIENT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DOCUMENT VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    USER_ROLE VARCHAR(20) NOT NULL,
    PROFILE_STATE VARCHAR(20) NOT NULL
);

-- Tabela Proposal
CREATE TABLE IF NOT EXISTS PROPOSAL (
    ID BIGSERIAL PRIMARY KEY,
    REQUEST_VALUE NUMERIC(19,2) NOT NULL,
    INSTALLMENTS_QTY NUMERIC(19,2) NOT NULL,
    MONTHLY_INCOME NUMERIC(19,2) NOT NULL,
    STATUS_ANALISIS VARCHAR(20) NOT NULL,
    CLIENT_ID BIGINT REFERENCES CLIENT(ID)
);

-- Tabela Contract
CREATE TABLE IF NOT EXISTS CONTRACT (
    ID BIGSERIAL PRIMARY KEY,
    SIGNED_AT TIMESTAMP NOT NULL,
    TOTAL_AMOUNT NUMERIC(19,2) NOT NULL,
    INSTALLMENTS_COUNT INTEGER NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    PROPOSAL_ID BIGINT REFERENCES PROPOSAL(ID),
    CLIENT_ID BIGINT REFERENCES CLIENT(ID)
);

-- Tabela Installment
CREATE TABLE IF NOT EXISTS INSTALLMENT (
    ID BIGSERIAL PRIMARY KEY,
    INSTALLMENT INTEGER NOT NULL,
    VALUE NUMERIC(19,2) NOT NULL,
    DUE_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CONTRACT_ID BIGINT REFERENCES CONTRACT(ID)
);

-- Tabela InterestRate
CREATE TABLE IF NOT EXISTS INTEREST_RATE (
    ID BIGSERIAL PRIMARY KEY,
    MIN_INSTALLMENT INTEGER NOT NULL,
    MAX_INSTALLMENT INTEGER NOT NULL,
    RATE_INCREMENT NUMERIC(19,6) NOT NULL,
    IOF_FIXED_RATE NUMERIC(19,6) NOT NULL
);

-- Tabela CalculationResult
CREATE TABLE IF NOT EXISTS CALCULATION_RESULT (
    ID BIGSERIAL PRIMARY KEY,
    APPLIED_BASE_RATE NUMERIC(19,6) NOT NULL,
    INCREMENT_RATE NUMERIC(19,6) NOT NULL,
    TOTAL_IOF_AMOUNT NUMERIC(19,2) NOT NULL,
    TOTAL_INTEREST_AMOUNT NUMERIC(19,2) NOT NULL,
    TOTAL_PAYABLE NUMERIC(19,2) NOT NULL,
    CALCULATION_DATE TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    PROPOSAL_ID BIGINT REFERENCES PROPOSAL(ID)
);
